name: Python to EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Create Executable with Data File
      run: pyinstaller --onefile --icon=wordle.ico --add-data "word_list.txt;." wordle.py
      # The '.' specifies the root directory of the executable where 'word_list.txt' will be placed
    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: wordle_exe  # This is the name of the artifact that will be uploaded
        path: dist/wordle.exe  # The path should match the output from PyInstaller
